name: auralive
description: "Go live and earn."
publish_to: 'none'

version: 6.0.0+8

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  bugsnag_flutter: ^4.1.3
  get: ^4.7.2
  visibility_detector: ^0.4.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  uuid: ^4.0.0
  shared_preferences: ^2.1.0
  connectivity_plus: ^6.1.4
  #  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1
  #  lottie: ^3.1.3
  lottie: ^3.3.1
  chewie: ^1.12.1
  #  chewie: ^1.10.0
  cached_network_image: ^3.4.1
  video_player: ^2.10.0
  #  video_player: ^2.9.5
  shimmer: ^3.0.0
  country_picker: ^2.0.27
  dotted_border: ^3.1.0
  #  dotted_border: ^2.1.0
  permission_handler: ^11.0.4
  #  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  socket_io_client: ^3.1.2
  #  camera: ^0.11.1
  camera: ^0.10.3+2
  flutter_spinkit: ^5.2.1
  firebase_auth: ^5.6.2
  #  firebase_auth: ^5.5.3
  firebase_core: ^3.15.1
  #  firebase_core: ^3.13.0
  preload_page_view: ^0.2.0
  firebase_messaging: ^15.2.9
  #  firebase_messaging: ^15.2.5
  #  google_sign_in: ^7.0.0
  google_sign_in: ^6.3.0
  google_mobile_ads: ^6.0.0  # *** >>> Google Ad Code <<< ***
  get_thumbnail_video: ^0.7.3
  image_picker: ^1.1.2
  #  ffmpeg_kit_flutter: ^6.0.3
  audioplayers: ^6.5.0
  #  audioplayers: ^6.4.0
  zego_express_engine: ^3.21.0
  #  zego_express_engine: ^3.20.5
  encrypt: ^5.0.3
  native_device_orientation: ^2.0.3
  flutter_svg: ^2.2.0
  #  flutter_svg: ^2.1.0
  record: ^6.0.0
  webview_flutter: ^4.13.0
  #  webview_flutter: ^4.11.0
  flutter_local_notifications: ^19.3.0

  dio: ^5.8.0+1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  #  mobile_scanner: ^6.0.10
  date_picker_plus: ^4.2.0
  http: ^1.4.0
  flutter_svga:
  #  svgaplayer_flutter: ^2.2.0
  in_app_purchase_android: ^0.4.0+2
  #  in_app_purchase_android: ^0.4.0+1
  in_app_purchase_storekit: ^0.4.3
  #  in_app_purchase_storekit: ^0.3.22+1
  vibration: ^3.1.3
  screenshot: ^3.0.0
  gallery_saver_plus: ^3.2.8
  #  gallery_saver_plus: ^3.2.4
  flutter_launcher_icons: ^0.14.4
  #  flutter_launcher_icons: ^0.14.3
  firebase_crashlytics: ^4.3.9
  #  firebase_crashlytics: ^4.3.7
  share_plus: ^11.0.0
  flutter_branch_sdk: ^8.5.0
  #  flutter_branch_sdk: ^7.1.0
  #  flutter_share: ^2.0.0
  readmore: ^3.0.0
  device_info_plus: ^11.5.0
  #  device_info_plus: ^10.1.0
  blurrycontainer: ^2.1.0
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.5.1+1
  #  video_trimmer: ^4.0.2
  video_trimmer: ^5.0.0

  #  wakelock_plus: ^1.2.10
  #  wakelock_plus: ^1.3.2
  #  loading_animation_widget: ^1.2.0+4
  loading_animation_widget: ^1.3.0
  sign_in_with_apple: ^7.0.1
  #  sign_in_with_apple: ^6.1.3
  quick_actions: ^1.1.0
  dismissible_page: ^1.0.2
  photo_view: ^0.15.0
  proste_indexed_stack: ^0.2.4





  # STORY RELATED PACKAGES
  provider: ^6.1.5
  image: ^4.5.4
  google_fonts: ^6.2.1
  image_gallery_saver_plus: ^4.0.1
  perfect_freehand: ^2.3.2
  align_positioned: ^5.0.1
  flutter_screenutil: ^5.9.3
  vs_media_picker: ^1.0.4
  story_view: ^0.16.6
  ffmpeg_kit_flutter_new: ^3.0.0
  audio_waveforms: ^1.3.0


  deepar_flutter_plus: ^0.2.0

dependency_overrides:
  connectivity_plus: 6.1.0
  device_info_plus: 11.0.0   # upgraded to fix web conflict
  share_plus: 10.0.2
  package_info_plus: 8.0.2
  shared_preferences: 2.2.2
  path: ^1.9.1
  http: ^1.0.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_app_logo.webp"
  min_sdk_android: 21


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/story_design_icons/
    - assets/images/
    - assets/lottie/
    - assets/effects/

  fonts:
    - family: SfProRegular
      fonts:
        - asset: assets/fonts/Sf-Pro-Regular.OTF

    - family: SfProMedium
      fonts:
        - asset: assets/fonts/Sf-Pro-Medium.OTF

    - family: SfProBold
      fonts:
        - asset: assets/fonts/Sf-Pro-Bold.OTF
